export enum ECarCardRegion {
  Vinnytsia = "vinnytsia",
  Volyn = "volyn",
  Dnipro = "dnipro",
  Donetsk = "donetsk",
  Zhytomyr = "zhytomyr",
  Zakarpattia = "zakarpattia",
  Zaporizhia = "zaporizhia",
  IvanoFrankivsk = "ivano_frankivsk",
  Kyiv = "kyiv",
  Kirovohrad = "kirovohrad",
  Lugansk = "lugansk",
  Lviv = "lviv",
  Mykolaiv = "mykolaiv",
  Odesa = "odesa",
  Poltava = "poltava",
  Rivne = "rivne",
  Sumy = "sumy",
  Ternopil = "ternopil",
  Kharkiv = "kharkiv",
  Kherson = "kherson",
  Khmelnytsky = "khmelnytsky",
  Cherkasy = "cherkasy",
  Chernihiv = "chernihiv",
  Chernivtsi = "chernivtsi",
}
